// Mocks generated by Mockito 5.4.4 from annotations
// in innoscripta_home_challenge/test/lib/data/repository/project/projects_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:http/http.dart' as _i2;
import 'package:innoscripta_home_challenge/core/configs/api/api_service.dart'
    as _i7;
import 'package:innoscripta_home_challenge/data/source/network/project/projects_api_service.dart'
    as _i3;
import 'package:innoscripta_home_challenge/domain/entity/project/project.dart'
    as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ProjectsApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockProjectsApiService extends _i1.Mock
    implements _i3.ProjectsApiService {
  MockProjectsApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  String get token => (super.noSuchMethod(
        Invocation.getter(#token),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#token),
        ),
      ) as String);

  @override
  _i5.Future<String> getAll() => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [],
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getAll,
            [],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> create(Map<String, dynamic>? project) =>
      (super.noSuchMethod(
        Invocation.method(
          #create,
          [project],
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #create,
            [project],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> update(_i6.Project? project) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [project],
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #update,
            [project],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #get,
            [id],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> delete(String? id) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [id],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Response> makeRequest(
    _i7.RequestData? requestData, {
    String? orgId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeRequest,
          [requestData],
          {#orgId: orgId},
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #makeRequest,
            [requestData],
            {#orgId: orgId},
          ),
        )),
      ) as _i5.Future<_i2.Response>);
}
