// Mocks generated by Mockito 5.4.4 from annotations
// in innoscripta_home_challenge/test/presentation/provider/task/task_state_notifier_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:io' as _i3;

import 'package:innoscripta_home_challenge/domain/entity/task/task.dart' as _i2;
import 'package:innoscripta_home_challenge/domain/use_cases/task/task_storage_use_cases.dart'
    as _i6;
import 'package:innoscripta_home_challenge/domain/use_cases/task/tasks_use_cases.dart'
    as _i4;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeTask_0 extends _i1.SmartFake implements _i2.Task {
  _FakeTask_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeDuration_1 extends _i1.SmartFake implements Duration {
  _FakeDuration_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeHttpClientRequest_2 extends _i1.SmartFake
    implements _i3.HttpClientRequest {
  _FakeHttpClientRequest_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TasksUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockTasksUseCases extends _i1.Mock implements _i4.TasksUseCases {
  MockTasksUseCases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<_i2.Task> create(_i2.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [task],
        ),
        returnValue: _i5.Future<_i2.Task>.value(_FakeTask_0(
          this,
          Invocation.method(
            #create,
            [task],
          ),
        )),
      ) as _i5.Future<_i2.Task>);

  @override
  _i5.Future<_i2.Task> update(_i2.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [task],
        ),
        returnValue: _i5.Future<_i2.Task>.value(_FakeTask_0(
          this,
          Invocation.method(
            #update,
            [task],
          ),
        )),
      ) as _i5.Future<_i2.Task>);

  @override
  _i5.Future<void> delete(_i2.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [task],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> close(_i2.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #close,
          [task],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Task> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i5.Future<_i2.Task>.value(_FakeTask_0(
          this,
          Invocation.method(
            #get,
            [id],
          ),
        )),
      ) as _i5.Future<_i2.Task>);

  @override
  _i5.Future<List<_i2.Task>> getAll(String? projectId) => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [projectId],
        ),
        returnValue: _i5.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i5.Future<List<_i2.Task>>);
}

/// A class which mocks [TaskStorageUseCases].
///
/// See the documentation for Mockito's code generation for more information.
class MockTaskStorageUseCases extends _i1.Mock
    implements _i6.TaskStorageUseCases {
  MockTaskStorageUseCases() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i5.Future<List<_i2.Task>> getClosedTasks() => (super.noSuchMethod(
        Invocation.method(
          #getClosedTasks,
          [],
        ),
        returnValue: _i5.Future<List<_i2.Task>>.value(<_i2.Task>[]),
      ) as _i5.Future<List<_i2.Task>>);

  @override
  _i5.Future<void> saveClosedTasks(List<_i2.Task>? tasks) =>
      (super.noSuchMethod(
        Invocation.method(
          #saveClosedTasks,
          [tasks],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> clearClosedTasks() => (super.noSuchMethod(
        Invocation.method(
          #clearClosedTasks,
          [],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);
}

/// A class which mocks [HttpClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockHttpClient extends _i1.Mock implements _i3.HttpClient {
  MockHttpClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  Duration get idleTimeout => (super.noSuchMethod(
        Invocation.getter(#idleTimeout),
        returnValue: _FakeDuration_1(
          this,
          Invocation.getter(#idleTimeout),
        ),
      ) as Duration);

  @override
  set idleTimeout(Duration? _idleTimeout) => super.noSuchMethod(
        Invocation.setter(
          #idleTimeout,
          _idleTimeout,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set connectionTimeout(Duration? _connectionTimeout) => super.noSuchMethod(
        Invocation.setter(
          #connectionTimeout,
          _connectionTimeout,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set maxConnectionsPerHost(int? _maxConnectionsPerHost) => super.noSuchMethod(
        Invocation.setter(
          #maxConnectionsPerHost,
          _maxConnectionsPerHost,
        ),
        returnValueForMissingStub: null,
      );

  @override
  bool get autoUncompress => (super.noSuchMethod(
        Invocation.getter(#autoUncompress),
        returnValue: false,
      ) as bool);

  @override
  set autoUncompress(bool? _autoUncompress) => super.noSuchMethod(
        Invocation.setter(
          #autoUncompress,
          _autoUncompress,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userAgent(String? _userAgent) => super.noSuchMethod(
        Invocation.setter(
          #userAgent,
          _userAgent,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set authenticate(
          _i5.Future<bool> Function(
            Uri,
            String,
            String?,
          )? f) =>
      super.noSuchMethod(
        Invocation.setter(
          #authenticate,
          f,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set connectionFactory(
          _i5.Future<_i3.ConnectionTask<_i3.Socket>> Function(
            Uri,
            String?,
            int?,
          )? f) =>
      super.noSuchMethod(
        Invocation.setter(
          #connectionFactory,
          f,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set findProxy(String Function(Uri)? f) => super.noSuchMethod(
        Invocation.setter(
          #findProxy,
          f,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set authenticateProxy(
          _i5.Future<bool> Function(
            String,
            int,
            String,
            String?,
          )? f) =>
      super.noSuchMethod(
        Invocation.setter(
          #authenticateProxy,
          f,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set badCertificateCallback(
          bool Function(
            _i3.X509Certificate,
            String,
            int,
          )? callback) =>
      super.noSuchMethod(
        Invocation.setter(
          #badCertificateCallback,
          callback,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set keyLog(dynamic Function(String)? callback) => super.noSuchMethod(
        Invocation.setter(
          #keyLog,
          callback,
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i5.Future<_i3.HttpClientRequest> open(
    String? method,
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #open,
          [
            method,
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #open,
            [
              method,
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> openUrl(
    String? method,
    Uri? url,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #openUrl,
          [
            method,
            url,
          ],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #openUrl,
            [
              method,
              url,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> get(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #get,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #get,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> getUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #getUrl,
          [url],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #getUrl,
            [url],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> post(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #post,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #post,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> postUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #postUrl,
          [url],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #postUrl,
            [url],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> put(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #put,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #put,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> putUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #putUrl,
          [url],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #putUrl,
            [url],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> delete(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #delete,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #delete,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> deleteUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #deleteUrl,
          [url],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #deleteUrl,
            [url],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> patch(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #patch,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #patch,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> patchUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #patchUrl,
          [url],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #patchUrl,
            [url],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> head(
    String? host,
    int? port,
    String? path,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #head,
          [
            host,
            port,
            path,
          ],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #head,
            [
              host,
              port,
              path,
            ],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  _i5.Future<_i3.HttpClientRequest> headUrl(Uri? url) => (super.noSuchMethod(
        Invocation.method(
          #headUrl,
          [url],
        ),
        returnValue:
            _i5.Future<_i3.HttpClientRequest>.value(_FakeHttpClientRequest_2(
          this,
          Invocation.method(
            #headUrl,
            [url],
          ),
        )),
      ) as _i5.Future<_i3.HttpClientRequest>);

  @override
  void addCredentials(
    Uri? url,
    String? realm,
    _i3.HttpClientCredentials? credentials,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addCredentials,
          [
            url,
            realm,
            credentials,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void addProxyCredentials(
    String? host,
    int? port,
    String? realm,
    _i3.HttpClientCredentials? credentials,
  ) =>
      super.noSuchMethod(
        Invocation.method(
          #addProxyCredentials,
          [
            host,
            port,
            realm,
            credentials,
          ],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void close({bool? force = false}) => super.noSuchMethod(
        Invocation.method(
          #close,
          [],
          {#force: force},
        ),
        returnValueForMissingStub: null,
      );
}
