// Mocks generated by Mockito 5.4.4 from annotations
// in innoscripta_home_challenge/test/lib/data/repository/task/tasks_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:http/http.dart' as _i2;
import 'package:innoscripta_home_challenge/core/configs/api/api_service.dart'
    as _i7;
import 'package:innoscripta_home_challenge/data/source/network/task/tasks_api_service.dart'
    as _i3;
import 'package:innoscripta_home_challenge/domain/entity/task/task.dart' as _i6;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeResponse_0 extends _i1.SmartFake implements _i2.Response {
  _FakeResponse_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [TasksApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockTasksApiService extends _i1.Mock implements _i3.TasksApiService {
  MockTasksApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  String get baseUrl => (super.noSuchMethod(
        Invocation.getter(#baseUrl),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#baseUrl),
        ),
      ) as String);

  @override
  String get token => (super.noSuchMethod(
        Invocation.getter(#token),
        returnValue: _i4.dummyValue<String>(
          this,
          Invocation.getter(#token),
        ),
      ) as String);

  @override
  _i5.Future<String> getAll(String? projectId) => (super.noSuchMethod(
        Invocation.method(
          #getAll,
          [projectId],
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #getAll,
            [projectId],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> create(Map<String, dynamic>? task) => (super.noSuchMethod(
        Invocation.method(
          #create,
          [task],
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #create,
            [task],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> update(_i6.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #update,
          [task],
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #update,
            [task],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<String> get(String? id) => (super.noSuchMethod(
        Invocation.method(
          #get,
          [id],
        ),
        returnValue: _i5.Future<String>.value(_i4.dummyValue<String>(
          this,
          Invocation.method(
            #get,
            [id],
          ),
        )),
      ) as _i5.Future<String>);

  @override
  _i5.Future<void> delete(_i6.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #delete,
          [task],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<void> close(_i6.Task? task) => (super.noSuchMethod(
        Invocation.method(
          #close,
          [task],
        ),
        returnValue: _i5.Future<void>.value(),
        returnValueForMissingStub: _i5.Future<void>.value(),
      ) as _i5.Future<void>);

  @override
  _i5.Future<_i2.Response> makeRequest(
    _i7.RequestData? requestData, {
    String? orgId,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #makeRequest,
          [requestData],
          {#orgId: orgId},
        ),
        returnValue: _i5.Future<_i2.Response>.value(_FakeResponse_0(
          this,
          Invocation.method(
            #makeRequest,
            [requestData],
            {#orgId: orgId},
          ),
        )),
      ) as _i5.Future<_i2.Response>);
}
